import { ChapterDefinition } from '@/types/plano';

export const CHAPTERS: ChapterDefinition[] = [
  // === Capítulos 1-3: Texto Livre ===
  {
    slug: 'apresentacao',
    order: 1,
    title: 'Capítulo 1 — Apresentação',
    shortTitle: 'Apresentação',
    type: 'text-free',
    fields: [
      { key: 'municipioUf', label: 'Município / UF' },
      { key: 'contextualizacao', label: 'Contextualização (base legal, processos participativos, motivação)' },
    ],
  },
  {
    slug: 'historico',
    order: 2,
    title: 'Capítulo 2 — Histórico da Cidade',
    shortTitle: 'Histórico',
    type: 'text-free',
    fields: [
      { key: 'origemHistorica', label: 'Origem histórica do município' },
      { key: 'fatoresCulturais', label: 'Fatores culturais relevantes para a mobilidade' },
      { key: 'fatoresHistoricos', label: 'Fatores históricos relevantes para a mobilidade' },
    ],
  },
  {
    slug: 'caracterizacao',
    order: 3,
    title: 'Capítulo 3 — Caracterização do Município',
    shortTitle: 'Caracterização',
    type: 'text-free',
    fields: [
      { key: 'caracteristicasGerais', label: 'Características gerais (população, área, divisão territorial)' },
      { key: 'atividadesEconomicas', label: 'Atividades econômicas predominantes' },
      { key: 'climaGeografia', label: 'Clima e geografia' },
      { key: 'festividades', label: 'Festividades e eventos que impactam a mobilidade' },
    ],
  },

  // === Capítulos 4-13: Estruturados ===
  {
    slug: 'transporte-coletivo',
    order: 4,
    title: 'Capítulo 4 — Transporte Público Coletivo',
    shortTitle: 'Transporte Coletivo',
    type: 'structured',
    note: 'Se o município não possui serviço de transporte público coletivo, descreva no diagnóstico a situação atual e as necessidades identificadas.',
    objectives: [
      'Melhorar a qualidade do serviço de transporte público coletivo',
      'Ampliar a cobertura do transporte público coletivo',
      'Reduzir o tempo de viagem no transporte público',
      'Garantir a acessibilidade universal no transporte coletivo',
      'Promover a integração modal',
      'Adequar a tarifa à capacidade de pagamento da população',
      'Reduzir a emissão de poluentes pelo transporte coletivo',
    ],
    suggestedGoals: [
      'Frota de veículos',
      'Itinerários e linhas',
      'Frequência e horários',
      'Acessibilidade dos veículos',
      'Pontos de parada e terminais',
      'Tarifa e sistema de bilhetagem',
      'Informação ao usuário',
    ],
    suggestedActions: [
      'Realização de pesquisa de origem-destino',
      'Revisão do plano de linhas e itinerários',
      'Implantação de faixas exclusivas para ônibus',
      'Renovação e adequação da frota',
      'Implantação de sistema de bilhetagem eletrônica',
      'Adequação de pontos de parada (acessibilidade)',
      'Implantação de sistema de informação ao usuário',
      'Criação de conselho de transporte público',
      'Revisão do modelo de concessão/permissão',
    ],
  },
  {
    slug: 'circulacao-viaria',
    order: 5,
    title: 'Capítulo 5 — Circulação Viária',
    shortTitle: 'Circulação Viária',
    type: 'structured',
    objectives: [
      'Melhorar a fluidez do tráfego',
      'Reduzir o número de acidentes de trânsito',
      'Organizar o estacionamento em vias públicas',
      'Melhorar a sinalização viária',
      'Ordenar a circulação de veículos pesados',
      'Reduzir a emissão de poluentes por veículos automotores',
    ],
    suggestedGoals: [
      'Sinalização horizontal e vertical',
      'Semáforos e controladores',
      'Velocidade e segurança viária',
      'Estacionamento regulamentado',
      'Circulação de veículos pesados',
      'Fiscalização eletrônica',
      'Educação para o trânsito',
      'Redução de emissões',
    ],
    suggestedActions: [
      'Elaboração de plano de sinalização viária',
      'Implantação de semáforos inteligentes',
      'Criação de áreas de velocidade reduzida (Zona 30)',
      'Regulamentação de estacionamento rotativo',
      'Definição de rotas para veículos pesados',
      'Implantação de fiscalização eletrônica',
      'Campanhas de educação para o trânsito',
      'Plano de redução de acidentes',
      'Implantação de rotatórias',
      'Programa de inspeção veicular',
      'Revisão da hierarquia viária',
      'Plano de circulação para áreas centrais',
      'Regulamentação do transporte por aplicativo',
    ],
  },
  {
    slug: 'infraestruturas',
    order: 6,
    title: 'Capítulo 6 — Infraestruturas de Mobilidade',
    shortTitle: 'Infraestruturas',
    type: 'structured',
    objectives: [
      'Ampliar e qualificar a malha viária',
      'Melhorar as condições de pavimentação',
      'Adequar as calçadas para acessibilidade universal',
      'Implantar infraestrutura cicloviária',
      'Melhorar a iluminação pública nas vias',
      'Implantar infraestrutura de drenagem nas vias',
    ],
    suggestedGoals: [
      'Pavimentação de vias',
      'Calçadas e passeios',
      'Ciclovias e ciclofaixas',
      'Iluminação pública',
      'Drenagem urbana nas vias',
      'Pontes e viadutos',
      'Terminais e estações',
    ],
    suggestedActions: [
      'Elaboração de plano de pavimentação',
      'Programa de recuperação de calçadas',
      'Implantação de rede cicloviária',
      'Construção de bicicletários e paraciclos',
      'Melhoria da iluminação em corredores de transporte',
      'Construção/reforma de terminais de integração',
      'Programa de acessibilidade em calçadas',
      'Implantação de piso tátil em rotas acessíveis',
    ],
  },
  {
    slug: 'modos-nao-motorizados',
    order: 7,
    title: 'Capítulo 7 — Modos Não Motorizados',
    shortTitle: 'Não Motorizados',
    type: 'structured',
    objectives: [
      'Estimular o uso da bicicleta como meio de transporte',
      'Melhorar as condições para deslocamento a pé',
      'Garantir acessibilidade nos deslocamentos não motorizados',
      'Integrar modos não motorizados ao transporte público',
      'Promover a segurança dos pedestres e ciclistas',
    ],
    suggestedGoals: [
      'Rede cicloviária',
      'Bicicletários e paraciclos',
      'Sistema de bicicletas compartilhadas',
      'Calçadas acessíveis',
      'Travessias seguras para pedestres',
      'Arborização e sombreamento de rotas',
      'Sinalização para ciclistas e pedestres',
    ],
    suggestedActions: [
      'Elaboração de plano cicloviário',
      'Implantação de ciclovias e ciclofaixas',
      'Instalação de bicicletários em terminais e equipamentos públicos',
      'Implantação de sistema de bicicletas compartilhadas',
      'Programa de melhoria de calçadas',
      'Criação de rotas acessíveis',
      'Campanhas de estímulo ao uso da bicicleta',
      'Programa "Pedala [Município]"',
      'Criação de zonas de prioridade para pedestres',
    ],
  },
  {
    slug: 'acessibilidade',
    order: 8,
    title: 'Capítulo 8 — Acessibilidade Universal',
    shortTitle: 'Acessibilidade',
    type: 'structured',
    objectives: [
      'Garantir acessibilidade em todo o sistema de mobilidade',
      'Adequar o transporte público para pessoas com deficiência e mobilidade reduzida',
      'Eliminar barreiras arquitetônicas nas vias e espaços públicos',
      'Promover o desenho universal em novos projetos',
      'Capacitar profissionais do transporte em acessibilidade',
    ],
    suggestedGoals: [
      'Veículos acessíveis na frota de transporte público',
      'Pontos de parada acessíveis',
      'Rampas e rebaixamento de calçadas',
      'Piso tátil em rotas estratégicas',
      'Sinalização acessível (visual, tátil, sonora)',
      'Vagas reservadas para PCD',
    ],
    suggestedActions: [
      'Diagnóstico de acessibilidade do sistema de mobilidade',
      'Programa de adequação de calçadas e travessias',
      'Adaptação dos pontos de parada e terminais',
      'Adequação da frota de transporte coletivo',
      'Implantação de semáforos sonoros',
      'Capacitação de operadores e motoristas',
      'Criação de comitê de acessibilidade',
      'Fiscalização de vagas reservadas',
    ],
  },
  {
    slug: 'integracao-modal',
    order: 9,
    title: 'Capítulo 9 — Integração dos Modos de Transporte',
    shortTitle: 'Integração Modal',
    type: 'structured',
    objectives: [
      'Promover a integração entre os modos de transporte',
      'Implantar terminais de integração',
      'Criar sistema de bilhetagem integrada',
      'Facilitar a conexão entre transporte público e modos não motorizados',
      'Integrar o transporte municipal ao intermunicipal/metropolitano',
    ],
    suggestedGoals: [
      'Terminais de integração',
      'Bilhetagem integrada (temporal/espacial)',
      'Integração bicicleta-transporte público',
      'Integração com transporte intermunicipal',
      'Estacionamentos park-and-ride',
      'Pontos de conexão intermodal',
    ],
    suggestedActions: [
      'Estudo de viabilidade de terminais de integração',
      'Implantação de bilhetagem integrada',
      'Criação de bicicletários em terminais',
      'Definição de pontos de integração intermodal',
      'Convênio com operadores de transporte intermunicipal',
      'Implantação de estacionamentos de integração',
      'Sistema de informação integrada ao usuário',
    ],
  },
  {
    slug: 'polos-geradores',
    order: 10,
    title: 'Capítulo 10 — Polos Geradores de Viagens',
    shortTitle: 'Polos Geradores',
    type: 'structured',
    objectives: [
      'Identificar e monitorar polos geradores de viagens',
      'Mitigar impactos de grandes empreendimentos na mobilidade',
      'Exigir estudos de impacto viário para novos empreendimentos',
      'Promover a gestão da demanda de viagens',
      'Ordenar o uso do solo em relação à mobilidade',
    ],
    suggestedGoals: [
      'Cadastro de polos geradores de viagens',
      'Estudos de impacto viário (EIV)',
      'Medidas mitigadoras em empreendimentos existentes',
      'Integração com o plano diretor',
      'Gestão da demanda por estacionamento',
    ],
    suggestedActions: [
      'Levantamento dos polos geradores de viagens do município',
      'Regulamentação de estudos de impacto viário',
      'Definição de medidas mitigadoras padrão',
      'Criação de fundo de mobilidade (contrapartida de empreendimentos)',
      'Articulação com o plano diretor para uso do solo',
      'Programa de gestão de demanda (horários flexíveis, carona, teletrabalho)',
    ],
  },
  {
    slug: 'areas-vulneraveis',
    order: 11,
    title: 'Capítulo 11 — Áreas Vulneráveis',
    shortTitle: 'Áreas Vulneráveis',
    type: 'structured',
    objectives: [
      'Melhorar a mobilidade em áreas de vulnerabilidade social',
      'Garantir acesso ao transporte público em áreas periféricas',
      'Melhorar a infraestrutura viária em áreas vulneráveis',
      'Promover segurança nos deslocamentos em áreas vulneráveis',
      'Reduzir desigualdades de acesso à mobilidade',
    ],
    suggestedGoals: [
      'Cobertura do transporte público em áreas vulneráveis',
      'Infraestrutura viária em áreas vulneráveis',
      'Iluminação pública em rotas de acesso',
      'Calçadas e acessibilidade em áreas vulneráveis',
      'Tarifa social ou gratuidade',
    ],
    suggestedActions: [
      'Mapeamento de áreas vulneráveis e suas necessidades de mobilidade',
      'Extensão de linhas de transporte público',
      'Programa de pavimentação em áreas vulneráveis',
      'Melhoria de iluminação em rotas de acesso',
      'Implantação de tarifa social',
      'Programa de calçadas em áreas vulneráveis',
      'Criação de linhas de transporte sob demanda',
    ],
  },
  {
    slug: 'seguranca-viaria',
    order: 12,
    title: 'Capítulo 12 — Segurança Viária',
    shortTitle: 'Segurança Viária',
    type: 'structured',
    objectives: [
      'Reduzir mortes e lesões graves no trânsito',
      'Implantar medidas de moderação de tráfego',
      'Melhorar a segurança de pedestres e ciclistas',
      'Aprimorar a fiscalização de trânsito',
      'Promover educação e conscientização para o trânsito',
    ],
    suggestedGoals: [
      'Redução de acidentes fatais',
      'Pontos críticos de acidentes tratados',
      'Travessias seguras implantadas',
      'Áreas de velocidade reduzida (Zona 30)',
      'Equipamentos de fiscalização',
      'Campanhas de educação realizadas',
    ],
    suggestedActions: [
      'Mapeamento de pontos críticos de acidentes',
      'Implantação de medidas de traffic calming',
      'Criação de Zonas 30 em áreas escolares e residenciais',
      'Melhoria de travessias de pedestres',
      'Implantação de lombadas eletrônicas e radares',
      'Campanhas de segurança viária (Maio Amarelo)',
      'Programa de educação de trânsito nas escolas',
      'Fortalecimento da fiscalização de trânsito',
      'Criação de comitê de segurança viária',
    ],
  },
  {
    slug: 'logistica-urbana',
    order: 13,
    title: 'Capítulo 13 — Logística Urbana e Transporte de Carga',
    shortTitle: 'Logística Urbana',
    type: 'structured',
    objectives: [
      'Ordenar o transporte de carga na área urbana',
      'Reduzir conflitos entre carga e demais modos de transporte',
      'Definir horários e rotas para veículos de carga',
      'Regulamentar áreas de carga e descarga',
      'Promover a logística urbana sustentável',
    ],
    suggestedGoals: [
      'Regulamentação de horários de carga/descarga',
      'Rotas definidas para veículos de carga',
      'Áreas de carga e descarga sinalizadas',
      'Veículos de carga com restrição de circulação',
      'Logística de última milha sustentável',
    ],
    suggestedActions: [
      'Estudo de logística urbana do município',
      'Regulamentação de horários e locais de carga/descarga',
      'Definição de rotas para veículos pesados',
      'Implantação de áreas de carga/descarga demarcadas',
      'Estímulo à logística de última milha com veículos leves',
      'Regulamentação do transporte de produtos perigosos',
      'Criação de centro de distribuição urbana (CDU)',
    ],
  },

  // === Capítulo 14: Revisão e Atualização ===
  {
    slug: 'revisao-atualizacao',
    order: 14,
    title: 'Capítulo 14 — Revisão e Atualização do Plano',
    shortTitle: 'Revisão e Atualização',
    type: 'review',
    reviewFields: [
      { key: 'prazoAtualizacao', label: 'Prazo para atualização do plano (em anos)', type: 'number' },
      { key: 'revisoesPeriodicasSim', label: 'Serão realizadas revisões periódicas?', type: 'radio', options: ['Sim', 'Não'] },
      {
        key: 'avaliacaoSelected',
        label: 'Instrumentos de avaliação e monitoramento',
        type: 'checkbox-group',
        options: [
          'Consulta à sociedade civil',
          'Banco de dados e indicadores de mobilidade',
          'Indicadores de desempenho do transporte público',
        ],
      },
      { key: 'orgaoResponsavel', label: 'Órgão responsável pela revisão e atualização', type: 'textarea' },
      {
        key: 'instrumentoNormativo',
        label: 'Instrumento normativo para aprovação do plano',
        type: 'checkbox-group',
        options: ['Lei municipal', 'Decreto municipal'],
      },
    ],
  },
];

export function getChapterBySlug(slug: string): ChapterDefinition | undefined {
  return CHAPTERS.find((c) => c.slug === slug);
}

export function getChapterByOrder(order: number): ChapterDefinition | undefined {
  return CHAPTERS.find((c) => c.order === order);
}
